<a href="https://colab.research.google.com/github/SriVarshini15/Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#https://www.kaggle.com/code/themlphdstudent/learn-numpy-numpy-50-exercises-and-solution

#import

In [76]:
import numpy as np

In [77]:
list=np.array([1,2,3])
print(list)

[1 2 3]


In [78]:
list2=np.array([[1,2,3],[11,12,13]])
print(list2)

[[ 1  2  3]
 [11 12 13]]


In [79]:
list3=np.array([[1,2.1,3],[11,12,13]])
print(list3)

[[ 1.   2.1  3. ]
 [11.  12.  13. ]]


In [80]:
print(list.ndim)
print(list2.ndim)

1
2


In [81]:
print(list.shape)
print(list2.shape)

(3,)
(2, 3)


In [82]:
print(list.dtype)
print(list3.dtype)

int64
float64


In [83]:
print(list.size)
print(list2.size)

3
6


In [84]:
print(list.itemsize)
print(list3.itemsize)

8
8


In [85]:
l=np.array([[1,2,3,4,5,6,7],[8,9,90,80,70,60,50]],dtype='int16')
print(l.dtype)
print(l.itemsize)

int16
2


In [86]:
print(l.size * l.itemsize)
print(l.nbytes)

28
28


In [87]:
print(list3[1][2])
print(list3[1][-2])

13.0
12.0


In [88]:
print(list3[0,:])
print(list3[:,0])
print(l[0,1:-1:2])

[1.  2.1 3. ]
[ 1. 11.]
[2 4 6]


In [89]:
l

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 90, 80, 70, 60, 50]], dtype=int16)

In [90]:
l[1, 3] = 999
print(l)

[[  1   2   3   4   5   6   7]
 [  8   9  90 999  70  60  50]]


In [91]:
l[:,2]=[88,88]
l

array([[  1,   2,  88,   4,   5,   6,   7],
       [  8,   9,  88, 999,  70,  60,  50]], dtype=int16)

In [92]:
multi=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(multi)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [93]:
print(multi[1,0,0]) # 5

5


In [94]:
print(multi[:,1,:])
multi[:,1,:]=[[11,11],[22,22]]
print(multi)

[[3 4]
 [7 8]]
[[[ 1  2]
  [11 11]]

 [[ 5  6]
  [22 22]]]


In [95]:
z=np.zeros([2,3])
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [96]:
o=np.ones([2,3,4],dtype='int32')
o

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [97]:
f=np.full((1,3),99,dtype='float32')
f

array([[99., 99., 99.]], dtype=float32)

In [98]:
fl=np.full_like(multi,999)
fl

array([[[999, 999],
        [999, 999]],

       [[999, 999],
        [999, 999]]])

In [99]:
r=np.random.rand(4,2)
r

array([[0.575, 0.891],
       [0.209, 0.185],
       [0.108, 0.22 ],
       [0.979, 0.812]])

In [100]:
np.random.random_sample(multi.shape)

array([[[0.172, 0.816],
        [0.274, 0.432]],

       [[0.94 , 0.818],
        [0.336, 0.175]]])

In [101]:
np.random.randint(10,size=(3,3))

array([[7, 0, 2],
       [9, 9, 3],
       [2, 5, 8]])

In [102]:
np.random.randint(5,10,size=(3,3))

array([[6, 5, 9],
       [7, 5, 5],
       [7, 7, 6]])

In [103]:
np.identity( 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [104]:
arr=np.array([[1,2,3]])
new=np.repeat(arr,3,axis=0)
print(new)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [105]:
temp=np.zeros((5,5))
innertemp=np.ones((3,3))
innertemp[1,1]=9
temp[1:4,1:4]=innertemp
temp

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 9., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [106]:
n1=np.array([1,2,3])
n2=n1
n2[0]=99
print(n1)

[99  2  3]


In [107]:
n11=np.array([1,2,3])
n22=n11.copy()
n22[0]=99
print(n11)

[1 2 3]


In [108]:
z=np.array([1,2,3,4])
z+2


array([3, 4, 5, 6])

In [109]:
z-2

array([-1,  0,  1,  2])

In [110]:
z*2

array([2, 4, 6, 8])

In [111]:
z/2

array([0.5, 1. , 1.5, 2. ])

In [112]:
y=np.array([5,6,7,8])
z+y

array([ 6,  8, 10, 12])

In [113]:
np.sin(z)

array([ 0.841,  0.909,  0.141, -0.757])

In [114]:
np.cos(z)

array([ 0.54 , -0.416, -0.99 , -0.654])

In [115]:
x=np.ones((2,3))
w=np.full((3,2),2)
print(x)
print(w)
np.matmul(x,w)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [116]:
v=np.identity(3)
np.linalg.det(v) #determinant

np.float64(1.0)

#Statistics

In [117]:
stats=np.array([[1,2,3,4],[5,6,7,8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [118]:
np.min(stats)

np.int64(1)

In [119]:
np.min(stats,axis=0)

array([1, 2, 3, 4])

In [120]:
np.min(stats,axis=1)

array([1, 5])

In [121]:
np.max(stats,axis=0)

array([5, 6, 7, 8])

In [122]:
np.max(stats,axis=1)

array([4, 8])

In [123]:
np.sum(stats,axis=0)

array([ 6,  8, 10, 12])

In [124]:
np.sum(stats,axis=1)


array([10, 26])

#Reorganising Arrays

In [125]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

print('\n')
after=np.reshape(before,(8,1))
after2=np.reshape(before,(2,2,2))
print(after)
print('\n')
print(after2)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#Vertical Stacking

In [126]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

print(np.vstack([v1,v2]))
print('\n')
print(np.vstack([v1,v2,v1]))

[[1 2 3 4]
 [5 6 7 8]]


[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]


#Horizontal Stacking

In [127]:
h1=np.array([1,2,3,4])
h2=np.array([5,6,7,8])

print(np.hstack([h1,h2]))

print('\n')

h3=np.ones((2,3))
h4=np.zeros((2,2))

print(np.hstack((h3,h4)))

[1 2 3 4 5 6 7 8]


[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]


#Load Dataset

In [128]:
fileData=np.loadtxt('/content/numpysampleset.txt',delimiter=',')
fileData

array([[  1.,   2.,   3., ...,   8.,   9.,   0.],
       [ 11.,  22.,  33., ...,  88.,  99.,  90.],
       [111., 222., 333., ..., 888., 999., 900.]])

In [129]:
fileData.astype('int32') #will be back to float and not inplace

array([[  1,   2,   3, ...,   8,   9,   0],
       [ 11,  22,  33, ...,  88,  99,  90],
       [111, 222, 333, ..., 888, 999, 900]], dtype=int32)

In [130]:
fileData

array([[  1.,   2.,   3., ...,   8.,   9.,   0.],
       [ 11.,  22.,  33., ...,  88.,  99.,  90.],
       [111., 222., 333., ..., 888., 999., 900.]])

In [131]:
fileData =fileData.astype('int32')
fileData

array([[  1,   2,   3, ...,   8,   9,   0],
       [ 11,  22,  33, ...,  88,  99,  90],
       [111, 222, 333, ..., 888, 999, 900]], dtype=int32)

#Boolean Masking and Advanced indexing

In [132]:
fileData>50

array([[False, False, False, ..., False, False, False],
       [False, False, False, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [133]:
fileData[fileData>50]

array([ 55,  66,  77, ..., 888, 999, 900], dtype=int32)

In [134]:
u=np.array([1,2,3,4,5,6,7,8,9])
u[[1,4,8]]

array([2, 5, 9])

In [135]:
np.any(fileData>50,axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [136]:
np.any(fileData>50,axis=1)

array([False,  True,  True])

In [137]:
np.all(fileData>50,axis=0)

array([False, False, False, False, False, False, False, False, False,
       False])

In [138]:
fileData[(fileData>50) & (fileData<100)]

array([55, 66, 77, 88, 99, 90], dtype=int32)

In [139]:
((fileData>50) & (fileData<100))

array([[False, False, False, ..., False, False, False],
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ..., False, False, False]])

In [140]:
r=np.arange(10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
t= np.repeat(1, 10).reshape(2,-1)
t

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [142]:
s=np.arange(10).reshape(2,-1)
s

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [143]:
q=np.array([1, 2, 3])
np.repeat(q, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [144]:
p = np.array([1, 2, 3])
np.tile(p, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

np.r_[ ... ]
This concatenates the two arrays created above.

In [145]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]
#np.hstack((np.repeat(a, 3), np.tile(a, 3)))

array([1, 1, 1, ..., 1, 2, 3])

#common items between a and b

In [146]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

#From array a remove all items present in array b

In [147]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

#positions where elements match

In [148]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [149]:
# Question: Swap columns 1 and 2 in the array arr.

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')
arr

# Solution

print("\nModified array")
arr[:, [1,0,2]]

Original array

Modified array


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [150]:
# Question: Swap rows 1 and 2 in the array arr:

# Input:

arr = np.arange(9).reshape(3,3)
print('Original array')
arr

# Solution

print("\nModified array")
arr[[1,0,2], :]

Original array

Modified array


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [151]:
# Question: Reverse the rows of a 2D array arr.

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')
arr

# Solution

print("\nModified array")
arr[::-1, :]

Original array

Modified array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [152]:
# Question: Reverse the columns of a 2D array arr.

# Input: arr = np.arange(9).reshape(3,3)

# Solution

arr = np.arange(9).reshape(3,3)
print('Original array')
arr


print("\nModified array")
arr[:, ::-1]

Original array

Modified array


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [153]:
# Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

# Solution:

rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[7.646, 9.784, 5.879],
       [5.592, 9.315, 5.374],
       [9.125, 9.181, 5.377],
       [5.057, 5.242, 6.786],
       [8.328, 5.057, 5.54 ]])

In [154]:
# Question: Print or show only 3 decimal places of the numpy array rand_arr.

# Input: rand_arr = np.random.random((5,3))

rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.901, 0.795, 0.811],
       [0.64 , 0.625, 0.146],
       [0.57 , 0.065, 0.313],
       [0.217, 0.527, 0.427],
       [0.983, 0.14 , 0.748]])

In [155]:
# Pretty print rand_arr by suppressing the scientific notation (like 1e10)

# Input:
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=False)
rand_arr

# Output:
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

np.set_printoptions(suppress=True)
rand_arr
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

array([[0.001, 0.   , 0.   ],
       [0.001, 0.   , 0.   ],
       [0.001, 0.001, 0.   ]])

In [156]:
# Question: Limit the number of items printed in python numpy array a to a maximum of 6 elements.
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [157]:
# Question: Print the full numpy array a without truncating.

# Input: np.set_printoptions(threshold=6)
# a = np.arange(15)
# a

# Output: a
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Solution

a = np.arange(15)


np.set_printoptions(threshold=15)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])